-- Create Student Non-Technical Events Table
CREATE TABLE IF NOT EXISTS student_non_technical (
  id INT PRIMARY KEY AUTO_INCREMENT,
  student_id VARCHAR(50) NOT NULL,
  student_name VARCHAR(255) NOT NULL,
  year_of_study VARCHAR(50) NOT NULL,
  event_attended VARCHAR(100) NOT NULL,
  club_id INT,
  club_events TEXT,
  other_event_specify TEXT,
  event_start_date DATE NOT NULL,
  event_end_date DATE NOT NULL,
  event_duration INT NOT NULL,
  event_location VARCHAR(255) NOT NULL,
  event_organiser VARCHAR(100) NOT NULL,
  organisor_name_other VARCHAR(255),
  event_level VARCHAR(50) NOT NULL,
  country VARCHAR(100),
  state VARCHAR(100),
  within_bit VARCHAR(10) NOT NULL,
  home_department VARCHAR(10),
  role_in_event VARCHAR(50) NOT NULL,
  role_specify_organised TEXT,
  role_specify_participated TEXT,
  status VARCHAR(50) NOT NULL,
  prize_type VARCHAR(50),
  prize_amount INT,
  social_activity_involved VARCHAR(10) NOT NULL,
  social_activity_name VARCHAR(255),
  time_spent_hours INT NOT NULL,
  interdisciplinary VARCHAR(10) NOT NULL,
  interdisciplinary_dept INT,
  other_dept_student_count INT,
  certificate_proof_path VARCHAR(500),
  iqac_verification VARCHAR(50) DEFAULT 'initiated',
  iqac_rejection_remarks TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(50),
  
  INDEX idx_student_id (student_id),
  INDEX idx_status (status),
  INDEX idx_iqac_verification (iqac_verification),
  INDEX idx_event_level (event_level),
  INDEX idx_created_at (created_at),
  CONSTRAINT fk_student_non_technical_club FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL,
  CONSTRAINT fk_student_non_technical_dept FOREIGN KEY (interdisciplinary_dept) REFERENCES departments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
